config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root "timeline#get_timeline", as: "authenticated_root"
  end

  root 'home#index'

  devise_for :users, controllers: {sessions: 'users/sessions', passwords: 'users/passwords', confirmations: 'users/confirmations',registrations: 'users/registrations', unlocks: 'users/unlocks', omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resource :posts
  
  get '/autocomplete_user_email' => 'timeline#autocomplete_user_email'
  post '/create_post_remote' =>'post#create_post_remote'  
  get '/like_post_remote' =>'like#like_post_remote'
  get '/users' => 'follow#get_all_users'
  get '/follow' => 'follow#follow'
  get '/user_profile' => 'profile#show'
  get '/edit/:username' => 'profile#edit', as: 'edit_profile'
  get '/check_field_validations' => 'profile#check_fields_validity'
  get '/search_username' => 'follow#search_username'
  get '/show_profile_remote' => 'follow#show_profile_remote'

end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
    autocomplete :user, :email, full: true
    before_action :authenticate_user!
    

    def get_timeline
        @post=Post.new
        @posts=current_user.feed
        @page_count = current_user.page_count
    end    


    


   


end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/timeline/_post.html.erb
<div class="post-image-container">
    <%= image_tag 'sample.jpg', id: 'post-img' %>
</div>
<div class="post-content-container">
    <p>
    <%=post.title%><br>
    <%=post.description%><br>
    <%=post.user.email%><br>
    <%=post.created_at%>
    </p>
    <%if post.likes.where(user_id: current_user.id).first%>
        <%= link_to "UnLike", url_for(controller: :like, action: :like_post_remote, post_id: post.id), remote: true,class: 'post_like_link', id: "post_#{post.id}" %>
    <%else%>
        <%= link_to "Like", url_for(controller: :like, action: :like_post_remote, post_id: post.id), remote: true, class: 'post_like_link', id: "post_#{post.id}" %>
    <%end%>   
</div>    

app/views/timeline/get_timeline.html.erb
<h1> Hey this is your timeline </h1>
<%= constant_string %>
<br>
<%= form_for @post, url: create_post_remote_path, remote: true do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="">
    <%= f.submit %>
  </div>
   <span id="letters">0</span>
<% end %>
<br>

<% form_tag '/', method: :get do %>

    <%=   autocomplete_field_tag 'email', '', autocomplete_user_email_path, :size => 20 %>
    <br>
    <%= submit_tag 'search' %>
<% end %>


<% if @posts!=nil%>
  <div class="posts-parent-container">
    <% @posts.each do |post| %>
      <div class="post-container">
        <%= render 'post' , post: post %>
      </div>  
    <% end %>
  </div>  
<% end %>